### ISSUE TITLE
Waiting time more than 30sec

### ISSUE THREAD

**Issue by hugolino** [RogerioBlanco/PixelCanvasBot#61]
Hi, the bot is very good, but i may have some issues,

Sometimes, the bot doesn't fill a square, and when i fill it manually i realize that it's a square with more than 30seconds of waiting time, so i was wondering if it's related.

Also, some time the program cannot print a pixel, it stay in loop with an error "Oh no, an error occurred. Trying again.", i have to restart it.

Anyway thank you !

**Comment by Qh0stM4N** [comment]
@hugolino bot use same validation key browser. You put a pixel for browser; bot it is affected by it and the waiting period is extended (renewed). 

waiting times are sent from the pixelcanvas.io server, we use the value sent. we increase it with a small randomly generated value to hide our robot.

the situation is something PixelCanvas can do. in order to avoid spoiling real users, maybe the first couple of colors may have gotten us to leave faster.

I try to help if you can give detailed information about where the error occurred and what lines , your operation system, python version, network status or modules,  it is in.

**Comment by hugolino** [comment]
Hi, i use Mac OS X Sierra (10.12.3) with Python 2.7.14.

The error show up randomly, anytimes it shoes the waiting time was between 30sec and 1min, but if it's more than 1 min the bot runs perfectly, if it less than 30sec also.

They're some pixel it cannot print, so i have to do it manually, and relunch the bot because it start looping trying to reprint the pixel but an error show up.

Don't know if i was clear, sorry for by bad english too

**Comment by Qh0stM4N** [comment]
hım maybe problem image caching. 
type output from this commands
`$ git log`
and need your image if it is not private  -who draws a special photo pixelcanvas.io :)-

**Comment by Qh0stM4N** [comment]
closed issue end of active life. Bot and your browser uses some fingerprint. You pixel place bot or browser, You can't drop a pixel from the internet browser at the same time as the bot is running.
